### PR TITLE
Fix LZ2 decompression issues

### LINKED ISSUE #22: LZ2 decompression issues (i believe)
A friend and I wanted to start a smw editor in rust with egui until we bumped into this more progressed project destroying our plans 😅 

There are some issues that got my attention in the LZ2 decompression code:

## Repeat command implementation

A look in the assembly of the Repeat command (at the address 00B966) (stolen from https://github.com/IsoFrieze/SMWDisX)

```asm
    JSR ReadByte
    XBA
    JSR ReadByte
 if ver_has_rev_gfx(!_VER)                    ;\==================== J & E1 ===================
    XBA                                       ;! ThinkingFace
 endif                                        ;/===============================================
    TAX
LOOP:
    PHY
    TXY
    LDA.B [_TMP],Y
    TYX
    PLY
    STA.B [_TMP],Y
    INY
    INX
    REP #$20                                  ; A->16
    DEC.B GraphicsUncompPtr
    SEP #$20                                  ; A->8
    BNE LOOP
    JMP NEXT_COMMAND
```

reveals the behaviour of this routine to always copy `length` bytes (`length` is stored in the Y register).
So if our currently compressed data would be for example `[1, 2, 3, 4]` and we got a
repeat command to copy 6 bytes starting from address 2 your code would result in
`[1, 2, 3, 4, 3, 4, 0, 0]`
But the assembly would do following steps:
1. `[1, 2, 3, 4, 3]`
2. `[1, 2, 3, 4, 3, 4]`
3. `[1, 2, 3, 4, 3, 4, 3]`
4. `[1, 2, 3, 4, 3, 4, 3, 4]`

I wrote a small test to check for this behaviour

```rust
#[test]
fn test_slice_repeat() {
    let compressed = [
        // Insert [1, 2, 3, 4]
        (0b011 << 5) | (4 - 1),
        1,
        // Repeat 7 bytes from address 1
        (0b100 << 5) | (7 - 1),
        0,
        1,
    ];
    let res = super::decompress(&compressed);
    const EXPECTED: &'static [u8] = &[1, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2];
    match res.as_ref().map(Vec::as_slice) {
        Err(err) => panic!("decompression failed unexpectedly ({err})"),
        Ok(EXPECTED) => (),
        Ok(res) => panic!("decompression gave wrong results (got: {res:?}, expected: {EXPECTED:?})"),
    }
}
```
```
thread 'compression::lc_lz2::tests::test_slice_repeat' panicked at
'decompression gave wrong results (got: [1, 2, 3, 4, 2, 3, 4, 0, 0, 0, 0],
expected: [1, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2])', smwe_rom/src/compression/lc_lz2.rs
```

I also decompressed the original rom data with your code and a (maybe buggy) "fixed" version of your code and got 613 bytes differing in the result, so this actually changes something!

## Endianness

The disassembly from SMWDisX also shows different endianness in the repeat command. While your implementation does big endian and thus supports the U version, but at least the J & E1 versions (if I correctly interpret the assembly) do little endian, so this wouldn't work.

All following will never occur on the original ROM,
so it is up to you to decide if these are bugs

## Multiple possible values for the Repeat command

Technically the assembly (see disassembly code starting from address 00B8FF) will only check
for the MSB in the command to be 1, so the commands `101`, `110`, `111` would also address the repeat command in the original ROM (e.g. `11111100 00000000` would be a (long) repeat command with `length` = 1).

## 16-bit overflow

Technically the `output` data could be larger than 2^16 bytes, but in the SNES it is addressed by 16-bit and an 16-bit overflow in the `output` buffer would result in overwriting values from its beginning. This would also require a different handling of the Repeat command.

However, I am not sure if a 16-bit overflow (which could only occur in a hacked version of the game) in the output buffer would break the game anyway, making 16-bit overflow handling obsolete.

### PR DESCRIPTION
**Pull request by nat-rix**
Fixes #22

### CODE REVIEW

**Comment by nat-rix** [comment]
The part with the endianness ROM version check is not tested.
It would be nice, if anyone could test the gfx decompression
with all ROM versions (J, U, SS, E0, E1).
I have only the U version.
Maybe it worked before and I broke it (in the last commit) 😅

**Comment by eigenraven** [comment]
@nat-rix can you rebase onto main? One of our github actions broke over the last week apparently.

File: smwe_rom/src/compression/lc_lz2.rs [hunk 1]
```diff
@@ -43,24 +35,21 @@ pub fn decompress(input: &[u8]) -> Result<Vec<u8>, DecompressionError> {
...
-        let mut length = length as usize + 1;
-
-        if let Command::LongLength = command {
-            let real_command_bits = (chunk_header >> 2) & 0b111;
-            command =
-                Command::try_from(real_command_bits).map_err(|_| LcLz2Error::LongLengthCommand(real_command_bits))?;
-            let length_part_1 = chunk_header & 0b11;
-            let length_part_2 = *in_it.first().ok_or(LcLz2Error::LongLength)?;
-            length = (((length_part_1 as usize) << 8) | (length_part_2 as usize)) + 1;
+        let (command, length) = if chunk_header & 0xe0 == 0xe0 {
```
Comment (Adanos020) [inline smwe_rom/src/compression/lc_lz2.rs:39]: I'd change the `0xe0` to `0xE0` since we would like to keep our hex number literals consistent across the codebase.

File: smwe_rom/src/compression/lc_lz2.rs [hunk 2]
```diff
@@ -43,24 +35,21 @@ pub fn decompress(input: &[u8]) -> Result<Vec<u8>, DecompressionError> {
...
+            // long command
+            let next_byte = *in_it.first().ok_or(LcLz2Error::LongLength)?;
             in_it = &in_it[1..];
-        }
+            ((chunk_header >> 2) & 7, u16::from_le_bytes([next_byte, chunk_header & 3]))
+        } else {
+            // normal command
+            (chunk_header >> 5, u16::from(chunk_header & 0x1f))
```
Comment (Adanos020) [inline smwe_rom/src/compression/lc_lz2.rs:46]: Same thing here, `0x1f` -> `0x1F`.

File: smwe_rom/src/compression/lc_lz2.rs [hunk 3]
```diff
@@ -95,27 +84,93 @@ pub fn decompress(input: &[u8]) -> Result<Vec<u8>, DecompressionError> {
...
+                    let bytes;
+                    (bytes, in_it) = in_it.split_at(2);
+                    let from_bytes = if revised_gfx { u16::from_le_bytes } else { u16::from_be_bytes };
+                    let read_start = usize::from(from_bytes([bytes[0], bytes[1]]));
+                    if read_start >= output.len() {
+                        return Err(
+                            LcLz2Error::RepeatRangeOutOfBounds(read_start..read_start + length, output.len()).into()
+                        );
+                    }
+                    output.reserve(length);
```
Comment (Adanos020) [inline smwe_rom/src/compression/lc_lz2.rs:98]: Even though this code will run just fine, I'd prefer lines 98-104 to be wrapped in an `else` block for slightly increased readability.

File: smwe_rom/src/compression/lc_lz2.rs [hunk 4]
```diff
@@ -1,40 +1,32 @@
...
+/// This command has got a two-byte header:
+/// ```text
+/// 111CCCLL LLLLLLLL
+/// CCC:        Real command
+/// LLLLLLLLLL: Length
+/// ```
+const LONG_LENGTH: u8 = 0b111;
 
-pub fn decompress(input: &[u8]) -> Result<Vec<u8>, DecompressionError> {
+pub fn decompress(input: &[u8], revised_gfx: bool) -> Result<Vec<u8>, DecompressionError> {
```
Comment (Adanos020) [inline smwe_rom/src/compression/lc_lz2.rs:29]: I'd rename `revised_gfx` to something more generic like `little_endian_in_repeat`, since decompression code doesn't necessarily have to deal with graphics, even though GFX might be the only thing LZ2 is used for in vanilla SMW.

**Review by Adanos020 — CHANGES_REQUESTED** [review]
Excellent change set, only a few little stylistic adjustments are required, which I wrote about in the comments.

I ran this code with the (U) ROM and all graphics look correct.

**Review by Adanos020 — APPROVED** [review]
